# Generated by Django 5.2 on 2025-04-16 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountUsage',
        ),
    ]
