# Generated by Django 5.2 on 2025-04-17 07:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discount_type', models.CharField(choices=[('cart', 'Cart'), ('delivery', 'Delivery')], max_length=20)),
                ('discount_percent', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('max_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_usage_per_day', models.PositiveIntegerField()),
                ('target_customers', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
