name: Django CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Create and activate virtual environment
        run: |
          python -m venv venv  # Create virtual environment
          source venv/bin/activate  # Activate virtual environment
          
      - name: Install dependencies
        run: |
          source venv/bin/activate  # Ensure the virtual environment is active
          python -m pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt  # Install dependencies
          
      - name: Run migrations
        run: |
          source venv/bin/activate  # Ensure the environment is activated before running commands
          python manage.py migrate  # Run migrations

      - name: Run tests
        run: |
          source venv/bin/activate  # Ensure the environment is activated before running tests
          python -m pytest --maxfail=1 --disable-warnings -q  # Run tests using pytest
