name: Django CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m venv venv  # Create a virtual environment
          . venv/bin/activate  # Activate the virtual environment (works in bash)
          pip freeze
          python -m pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt  # Install dependencies

      - name: Run migrations
        run: |
          . venv/bin/activate  # Ensure the environment is activated before running commands
          python manage.py migrate  # Run migrations

      - name: Run tests
        run: |
          . venv/bin/activate  # Ensure the environment is activated
          pip install pytest>=6.0.0
          python -m pytest --maxfail=1 --disable-warnings -q  # Run tests using pytest
